### ISSUE TITLE
integrate signup front-end with backend

### ISSUE THREAD

**Issue by janmesh799** [janmesh799/Pro-Profile#4]

**Comment by siyaa12** [comment]
hey @janmesh799 , i would like to work on this issue. can you please assign this issue to me?

**Comment by janmesh799** [comment]
ohk @siyaa12 , i am assigning this issue to you.

**Comment by siyaa12** [comment]
made a PR regarding the issue

**Comment by janmesh799** [comment]
closing this issue. Thanks for Contributing
