### ISSUE TITLE
update UI of 404 Not found page

### ISSUE THREAD

**Issue by janmesh799** [janmesh799/Pro-Profile#6]

**Comment by siyaa12** [comment]
Can I work on this issue ?

**Comment by janmesh799** [comment]
@siyaa12  assigned you. best of luck

**Comment by siyaa12** [comment]
404 Not found page is already there what i have to do?

**Comment by janmesh799** [comment]
oh so, sorry . you have to update the UI of it.

**Comment by siyaa12** [comment]
@janmesh799  Created PR for the regarding the same Issue

**Comment by janmesh799** [comment]
@siyaa12 Merged your PR, thanks for contributing.
